name: build-ui

on:
  push:
    branches:
      - main
    paths:
      - "ui/**"
  pull_request:
    branches:
      - main
    paths:
      - "ui/**"

env:
  REGISTRY: ghcr.io

defaults:
  run:
    working-directory: ui/

jobs:
  node-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - name: Upload static files from build
        uses: actions/upload-artifact@v3
        with:
          name: static-files
          path: dist/
  docker-build:
    needs: node-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download static files from node-build
        uses: actions/download-artifact@v3
        with:
          name: static-files
          path: dist/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist/
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
